services:
  frontend:
    container_name: expense_tracker_frontend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5173:5173"
    networks:
      - expense_tracker_network
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: npm run dev
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  expense_tracker_network:
    driver: bridge

volumes:
  web_data: